services:
  ingress:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:1337:80"
    volumes:
      - "./docker-nginx.conf:/etc/nginx/nginx.conf:delegated"
  client:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/develop:delegated
      - /develop/node_modules
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/develop:delegated
      - /develop/node_modules
